In [ ]:
import numpy as np
# NumPy (Intermediate)
#  A weather station stores hourly temperature readings for 7 days in a NumPy array of shape (7, 24).
# Task:
# Find the daily maximum and minimum temperature
# Identify the day with the largest temperature variation
# Replace outliers beyond ±2 standard deviations with the mean temperature
temperatures = np.random.randint(1,100,(7,24))
print(temperatures)
highest = 0
day = 0
for i in range(0,7):
    high_temp = temperatures[i,0::].max()
    min_temp = temperatures[i,0::].min()
    print(f"Temperatures of day {i+1} is \n max temperature = {high_temp} \n min temperature = {min_temp}")
    if high_temp >= highest:
        highest = high_temp
        day = i+1
print(f"Day: {day} is the day with highest Temperature with {highest} Among 7 days")
mean = temperatures.mean()
print(mean)
std = temperatures.std()
sd1 =  2 * std
sd2 =  -2 * std
temperatures = np.array(np.where(temperatures > sd1, mean, temperatures),dtype = int)
temperatures = np.array( np.where(temperatures < sd2, mean, temperatures),dtype = int)

[[46  9 87 96 62 17 50 51 39 85 27 10 65 57 60 39 78 84 10 57 94 71 98 15]
 [76 68 33 34 86 55 50 40 81 70 24 14 58 65 61 57 60 91 59 62 63 40 60 92]
 [44 25 78 46 63 22 91 44 56 20 45 97 86 57 71 65 86 82 14 60  9 87 97 15]
 [62 12  6 35 56 25 33 81 70 28 95  3 83  5 52 75  7 57 18 53 80 51 47 71]
 [28 47  3 94  6 45 67 30  8 49 52 58 70  4  2  4 53 27 51 25 18 69 25 40]
 [41 61 66  7 65 55 39 63 60 92 69 20 18 10 13 59 48 47 26  4 94 84 53 43]
 [ 5 66 78 13 92 56 52 15 25 47 73 86  3 68 54  8 50 40 93 14 23 96 44 95]]
Temperatures of day 1 is 
 max temperature = 98 
 min temperature = 9
Temperatures of day 2 is 
 max temperature = 92 
 min temperature = 14
Temperatures of day 3 is 
 max temperature = 97 
 min temperature = 9
Temperatures of day 4 is 
 max temperature = 95 
 min temperature = 3
Temperatures of day 5 is 
 max temperature = 94 
 min temperature = 2
Temperatures of day 6 is 
 max temperature = 94 
 min temperature = 4
Temperatures of day 7 is 
 max temperature = 96 
 min

In [ ]:
print(temperatures)

[[46  9 49 49 49 17 50 51 39 49 27 10 49 49 49 39 49 49 10 49 49 49 49 15]
 [49 49 33 34 49 49 50 40 49 49 24 14 49 49 49 49 49 49 49 49 49 40 49 49]
 [44 25 49 46 49 22 49 44 49 20 45 49 49 49 49 49 49 49 14 49  9 49 49 15]
 [49 12  6 35 49 25 33 49 49 28 49  3 49  5 52 49  7 49 18 53 49 51 47 49]
 [28 47  3 49  6 45 49 30  8 49 52 49 49  4  2  4 53 27 51 25 18 49 25 40]
 [41 49 49  7 49 49 39 49 49 49 49 20 18 10 13 49 48 47 26  4 49 49 53 43]
 [ 5 49 49 13 49 49 52 15 25 47 49 49  3 49 54  8 50 40 49 14 23 49 44 49]]
